### PR TITLE
Add some information about preact-nx-observer

### PR DESCRIPTION
**Pull request by mseddon**
I recently wrote a tiny binding for Preact which implements the `mobx-react` `@observer` attribute. If you would like to reference it, I've given an example and a link to the repository.

### CODE REVIEW

**Comment by solkimicreb** [comment]
Sorry, I completely missed this PR somehow 😞 Can you indent the usage example the same way as the others are indented (2 space or 1 tab)? After that, it's good to go.

**Comment by mseddon** [comment]
No problem! I will correct that next week 😄

**Comment by mseddon** [comment]
All ready I think?

**Comment by solkimicreb** [comment]
Awesome, thanks!

**Comment by mseddon** [comment]
Thanks for such a tight library 😆

**Pull request merged**
